source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'R2S' do
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
  pod "MIBadgeButton-Swift", :git => 'https://github.com/mustafaibrahim989/MIBadgeButton-Swift.git', :branch => 'master'
  pod 'IQKeyboardManagerSwift', '4.0.6'
  pod 'KMPlaceholderTextView', '~> 1.3.0'
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
  pod 'SwiftyJSONRealmObject'
  pod 'GoogleMaps'
  pod 'M13Checkbox'
  pod 'Kingfisher'
  pod 'RealmSwift'
  pod 'FSCalendar'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Google/SignIn'
  pod 'NVActivityIndicatorView'
  pod 'SwiftSpinner'
  pod 'SwiftKeychainWrapper'
  pod 'DropDown'
  pod 'AMScrollingNavbar', '3.2.0'
end
